name: baodq_ssl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.20.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - gnutls=3.6.13=h85f3911_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_4
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h0b41bf4_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.0=h26f9b46_0
  - pillow=9.4.0=py310h023d228_1
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.14=hd12c33a_0_cpython
  - python_abi=3.10=8_cp310
  - pytorch=2.4.0=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py310h3406613_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.7.0=h924138e_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.4.0=py310_cu121
  - torchtriton=3.0.0=py310
  - torchvision=0.19.0=py310_cu121
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py310h7c4b9e2_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aenum==3.1.16
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - beartype==0.22.9
      - click==8.3.1
      - exceptiongroup==1.3.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - hydra-core==1.3.2
      - joblib==1.5.3
      - lightly==1.5.22
      - lightly-utils==0.0.2
      - lightning==2.6.0
      - lightning-bolts==0.7.0
      - lightning-utilities==0.15.2
      - markdown==3.10
      - multidict==6.7.0
      - omegaconf==2.3.0
      - packaging==25.0
      - platformdirs==4.5.1
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.2.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentry-sdk==2.48.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - typer-slim==0.20.1
      - typing-inspection==0.4.2
      - wandb==0.23.1
      - werkzeug==3.1.4
      - yarl==1.22.0
prefix: /mnt/disk1/miniconda3/envs/baodq_ssl
