_wandb:
    value:
        cli_version: 0.23.1
        e:
            n28fy81zgomqd2knas2o4d0hznrktoo5:
                email: hang.phungthu01@gmail.com
                executable: /mnt/disk1/miniconda3/envs/baodq_ssl/bin/python
                git:
                    commit: a7b1ed2bf46254f161f7b52f6f73cc93b193b021
                    remote: https://github.com/frichickens/Self-Supervised-Learning-comparisons.git/
                host: vaipe-Z790-UD-AX
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /mnt/disk4/baodq/resnet18_byol.py
                python: CPython 3.10.14
                root: .
                startedAt: "2025-12-22T17:58:14.170841Z"
                writerId: n28fy81zgomqd2knas2o4d0hznrktoo5
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.10.14
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": linux-x86_64
