_wandb:
    value:
        cli_version: 0.23.1
        e:
            zeyvb9t95d3bsi0oxtlt8elqxy47mm10:
                codePath: resnet18_byol.py
                codePathLocal: resnet18_byol.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "502392610816"
                        used: "421404467200"
                email: dinhquocbao.hust@gmail.com
                executable: /mnt/disk1/miniconda3/envs/baodq_ssl/bin/python
                git:
                    commit: a7b1ed2bf46254f161f7b52f6f73cc93b193b021
                    remote: https://github.com/frichickens/Self-Supervised-Learning-comparisons.git/
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-131c9a56-60f2-3bb0-7b04-575a2e52bd15
                host: vaipe-Z790-UD-AX
                memory:
                    total: "67163844608"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /mnt/disk4/baodq/Self-Supervised-Learning-comparisons/resnet18_byol.py
                python: CPython 3.10.14
                root: .
                startedAt: "2025-12-22T18:59:56.676180Z"
                writerId: zeyvb9t95d3bsi0oxtlt8elqxy47mm10
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.10.14
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": linux-x86_64
