_wandb:
    value:
        cli_version: 0.23.1
        e:
            4t2d6wfukwrczygd6cooiy377dl5w59s:
                codePath: train_lightly/model/downstream_projector.py
                codePathLocal: model/downstream_projector.py
                email: dinhquocbao.hust@gmail.com
                executable: /mnt/disk1/miniconda3/envs/baodq_ssl/bin/python
                git:
                    commit: dd29cf4d53e813d63c8ec4bcd037c0b90ee2e10e
                    remote: https://github.com/frichickens/Self-Supervised-Learning-comparisons.git/
                host: vaipe-Z790-UD-AX
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /mnt/disk4/baodq/Self-Supervised-Learning-comparisons/train_lightly/model/downstream_projector.py
                python: CPython 3.10.14
                root: /mnt/disk4/baodq/Self-Supervised-Learning-comparisons/train_lightly
                startedAt: "2025-12-22T19:44:55.102897Z"
                writerId: 4t2d6wfukwrczygd6cooiy377dl5w59s
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 13
                - 16
            "4": 3.10.14
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 256
epochs:
    value: 100
learning_rate:
    value: 0.1
optimizer:
    value: SGD
scheduler:
    value: CosineAnnealingLR
