name: medm
channels:
  - conda-forge
  - nvidia
  - robostack
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - nodejs=20.19.5=hf7ee748_0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.19=hd994cfb_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - absl-py==2.3.1
      - accelerate==0.32.1
      - aenum==3.1.16
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bert-score==0.3.13
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cmake==4.1.0
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - deepspeed==0.14.4
      - dill==0.4.0
      - dotenv==0.9.9
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - evaluate==0.4.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.119.0
      - ffmpy==0.6.3
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-pasta==0.2.0
      - gradio==5.20.0
      - gradio-client==1.7.2
      - groovy==0.1.2
      - grpcio==1.75.1
      - h11==0.16.0
      - h5py==3.15.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - ipykernel==6.29.5
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - keras==3.11.3
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - lightly==1.5.22
      - lightly-utils==0.0.2
      - lightning-utilities==0.15.2
      - lit==18.1.8
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - monai==1.3.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nibabel==5.2.1
      - ninja==1.13.0
      - nltk==3.8.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.17.0
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - peft==0.12.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pydantic==2.12.2
      - pydantic-core==2.41.4
      - pydicom==3.0.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.17.2
      - pyqtgraph==0.14.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qimage2ndarray==1.10.0
      - qtawesome==1.4.0
      - qtpy==2.4.3
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.2.0
      - rouge-score==0.1.2
      - ruff==0.14.0
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.5.1
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentence-transformers==5.2.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.46.0
      - shellingham==1.5.4
      - simple-slice-viewer==0.97
      - simpleitk==2.5.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.48.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - tf-keras==2.20.1
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tokenizers==0.19.1
      - tomlkit==0.13.3
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchmetrics==1.8.2
      - torchvision==0.16.2+cu118
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.42.4
      - triton==2.1.0
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - wandb==0.23.0
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/user01/miniconda3/envs/medm
